import { Form } from ".";

export default {
  title: "Components/Form",
  component: Form,
};

export const Default = {
  args: {
    className: {},
    textClassName: {},
    datePickerDropdownButtonsButtonText: "Select dates",
    datePickerDropdownButtonsButtonText1: "Select dates",
    textClassNameOverride: {},
    datePickerDropdownButtonsButtonText2: "Select dates",
    datePickerDropdownButtonsButtonText3: "Select dates",
    inputClassName: {},
    datePickerDropdownButtonsButtonText4: "Select dates",
    inputDropdownText: "All",
    inputDropdownText1: "All",
    inputDropdownText2: "All",
    datePickerDropdownButtonsButtonText5: "Select dates",
    inputClassNameOverride: {},
    textClassName1: {},
    textClassName2: {},
    textClassName3: {},
    button: "/img/button-32.svg",
    textClassName4: {},
    textClassName5: {},
    inputDropdownStateProp: "placeholder",
    inputDropdownSupportingText: true,
    inputDropdownText3: "abc",
    inputDropdownStateProp1: "placeholder",
    inputDropdownSupportingText1: true,
    inputDropdownText4: "abc",
    textClassName6: {},
    textClassName7: {},
    textClassName8: {},
    textClassName9: {},
    inputDropdownStateProp2: "placeholder",
    inputDropdownSupportingText2: true,
    inputDropdownText5: "abc",
    divClassName: {},
    textInputClassName: {},
    datePickerDropdownStateProp: "active",
    datePickerDropdownButtonsButtonTextClassName: {},
    datePickerDropdownStateProp1: "active",
    datePickerDropdownButtonsButtonTextClassNameOverride: {},
    divClassNameOverride: {},
    textInputClassNameOverride: {},
    datePickerDropdownStateProp2: "active",
    datePickerDropdownButtonsButtonDivClassName: {},
    datePickerDropdownStateProp3: "active",
    datePickerDropdownButtonsButtonDivClassNameOverride: {},
    inputClassName1: {},
    textInputClassName1: {},
    datePickerDropdownStateProp4: "active",
    datePickerDropdownButtonsButtonTextClassName1: {},
    inputDropdownStateProp3: "default",
    inputDropdownText6: "abc",
    inputDropdownStateProp4: "default",
    inputDropdownText7: "abc",
    inputDropdownStateProp5: "default",
    inputDropdownText8: "abc",
    datePickerDropdownStateProp5: "active",
    datePickerDropdownButtonsButtonTextClassName2: {},
    inputClassName2: {},
    inputClassName3: {},
    textClassName10: {},
    inputClassName4: {},
    textClassName11: {},
    inputClassName5: {},
    textClassName12: {},
    inputClassName6: {},
    textClassName13: {},
    inputClassName7: {},
    textClassName14: {},
    inputClassName8: {},
    textClassName15: {},
    inputClassName9: {},
    textClassName16: {},
    inputClassName10: {},
    textClassName17: {},
    inputClassName11: {},
    inputClassName12: {},
    inputClassName13: {},
    textClassName18: {},
    inputClassName14: {},
    textClassName19: {},
    inputClassName15: {},
    textClassName20: {},
    inputClassName16: {},
    inputClassName17: {},
    textClassName21: {},
    inputClassName18: {},
    textClassName22: {},
    inputClassName19: {},
    textClassName23: {},
    buttonsButtonStateProp: "default",
    inputClassName20: {},
    inputClassName21: {},
    inputDropdownText9: "Select payment status",
    inputDropdownText10: "Select payment method",
    inputClassName22: {},
    textClassName24: {},
    inputClassName23: {},
    textClassName25: {},
    inputClassName24: {},
    inputClassName25: {},
    textClassName26: {},
    inputClassName26: {},
    inputClassName27: {},
    textClassName27: {},
    inputClassName28: {},
    inputClassName29: {},
    textClassName28: {},
    inputClassName30: {},
    inputDropdownText11: "Select Sale Person",
    buttonClassName: {},
    inputType: "tel",
    inputType1: "tel",
    inputType2: "email",
  },
};
